function [good, mua, noise] = get_phy_labels()

% Note:
%   'cluster_si_unit_ids.tsv' only lists cluster_ids as originally exported
%   by SpikeInterface.
data = readtable('cluster_si_unit_ids.tsv', 'FileType', 'text', 'Delimiter', '\t');
data = table2array(data);

max_phy_ind = data(end,1);
phy2si = data(:,2);

good = [];
mua = [];
noise = [];

data = readtable('cluster_group.tsv', 'FileType', 'text', 'Delimiter', '\t');

for k = 1:size(data, 1)
    phy_ind = data{k,1};
    if phy_ind > max_phy_ind
        % For now, we don't handle clusters that were generated by manual
        % splits and merges in Phy
        cprintf('blue', 'Skipped phy_ind=%d\n', phy_ind);
    else
        si_ind = phy2si(phy_ind+1);
        label = data{k,2}{1};
        switch label
            case 'good'
                good = [good; si_ind];
            case 'mua'
                mua = [mua; si_ind];
            case 'noise'
                noise = [noise; si_ind];
        end
    end
end