function visualize_opto_cellmap(ds, info)

color_map = {info.results.inds.inhibited, 'c';
             info.results.inds.disinhibited, 'r';
             info.results.inds.other, 'w'};
ds.plot_cell_map(color_map);
title_str = sprintf('%s (%s): inhibited (%d, cyan); disinhibited (%d, red); no effect (%d, white)',...
    info.dataset_name,...
    info.settings.score_type,...
    info.results.num_inhibited,...
    info.results.num_disinhibited,...
    length(info.results.inds.other));
title(title_str);