function plot_raster_from_ds(ds, cell_idx, align_to)
% Assumes that the DaySummary includes only ST trials. Trial frame indices
% within the ds should be:
%   [Trial-start Motion-onset US-time Trial-end].
%
% Furthermore, visualization assumes that imaging frame rate is 15 Hz.
%
% Raster generation from DaySummary, which operates at the imaging _frame_
% level is less temporally accurate than methods that operate directly from
% Saleae time (e.g. ctxstr.vis.show_aligned_raster). However, this method
% may be useful for making use of existing codebase involving DaySummary
% and MultiDay objects.
%
% The raster generated by this function shows the entirety of the neural
% trace for all trials. This contrasts the behavior of
% `DaySummary.plot_cell_raster` which shows the portion of data that is
% common to all trials.

% By default, 
if ~exist('align_to', 'var')
    align_to = 2;
end

num_trials = ds.num_trials;
aligned_frames = zeros(num_trials, 4);

for k = 1:num_trials
    trial_frames = ds.trial_indices(k,:);
    aligned_frames(k,:) = trial_frames - trial_frames(align_to);
end
frame_lims = [min(aligned_frames(:,1)) max(aligned_frames(:,end))];

num_total_frames = frame_lims(2) - frame_lims(1) + 1;
R = nan(num_trials, num_total_frames);
for k = 1:num_trials
    trace = ds.trials(k).traces(cell_idx,:);
    offset = aligned_frames(k,1) - frame_lims(1) + 1;
    R(k,offset:offset+length(trace)-1) = trace;
end

% Plot raster with transparency
alpha = ones(size(R));
alpha(isnan(R)) = 0;
t = 1/15 * (frame_lims(1):frame_lims(2)); % Assumes 15 Hz data
imagesc(t, 1:num_trials, R, 'AlphaData', alpha)

% Additional annotation and graphical formatting
hold on;
plot([0 0], [0.5 num_trials+0.5], 'w:');
hold off;
ylabel('ST trial index');
switch align_to
    case 2
        xlabel('Time relative to motion onset (s)');
    case 3
        xlabel('Time relative to US (s)');
end
set(gca, 'TickLength', [0 0]);
