function show_behavior(behavior_data)
% Produces a very basic plot of velocity, reward delivery, and licks.
%
% Here, 'behavior_data' is the behavior struct that is generated by the
% function `parse_ctxstr.m`

t = behavior_data.velocity(:,1); % Time (s)
v = behavior_data.velocity(:,2); % Velocity (cm/s)

plot(t,v);
xlim([t(1) t(end)]);
xlabel('Time (s)');

v_min = min(v);
v_max = max(v);
v_range = 0.05*(v_max-v_min)*[-1 1] + [v_min v_max];
ylim(v_range);
ylabel('Velocity (cm/s)');
set(gca, 'TickLength', [0 0]);
zoom xon;

hold on;

num_rewards = length(behavior_data.us_times);
for k = 1:num_rewards
    us_time = behavior_data.us_times(k);
    plot(us_time*[1 1], v_range, 'k');
end

num_licks = length(behavior_data.lick_times);
for k = 1:num_licks
    lick_time = behavior_data.lick_times(k);
    plot(lick_time*[1 1], v_range, 'r');
end

hold off;
